### ISSUE TITLE
missed space in the API documentation

### ISSUE THREAD

**Issue by lia2790** [ADVRHumanoids/ROSEndEffectorDocs#2] opened 2020-06-29 08:02 UTC
Hi, I was rewatching the documentation about the project and I saw that in the website of the Documentation API missing some spaces as in the photo

<img width="1280" alt="Schermata 2020-06-29 alle 10 00 34" src="https://user-images.githubusercontent.com/15608027/85988569-85b86d00-b9ef-11ea-93a5-55bf2742a689.png">

then it is to be fixed. If you want I can but I do not know how to do it.

@liesrock @torydebra

**Comment by torydebra** [comment] 2020-06-29 08:33
Hi,
The api doc that is online is built from master branch, which has not been updated since a while. In the most recent versions (like devel branch) the typo should be fixed :

~~~
# Using the PROJECT_BRIEF tag one can provide an optional one line description
# for a project that appears at the top of each page and should give viewer a
# quick idea about the purpose of the project. Keep the description short.

PROJECT_BRIEF          = "ROS End-Effector package: provides a ROS-based set of standard interfaces 
                          to command robotics end-effectors in an agnostic fashion."
~~~

**Comment by lia2790** [comment] 2020-06-29 08:40
ok, so it is fixed, can we update in order to fix it definitely?

**Comment by torydebra** [comment] 2020-07-21 09:57
Seems that the problem is because the line in Doxyfile is divided in two rows. 
Not sure who updates the PROJECT_BRIEF variable and how; for now we can modify it manually in Doxyfile, let's remember this

**Closed as completed by torydebra** 2020-07-21 09:57 UTC
